import StoreProvider from "@/lib/provader";
import "./globals.css";
import Navbar from "@/componnet/Navbar";
import Fouter from '@/componnet/Fouter'


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#1B0119] w-screen  h-screen from-50% p-5 max-w-full max-auto">

        <StoreProvider>
          <Navbar />
          {children}
          <Fouter />
        </StoreProvider>




      </body>
    </html>
  );
}
